version: '3.8'

services:
  imgpressor:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-20971520}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT:-10}
    volumes:
      - ./public/optimized:/app/public/optimized
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - imgpressor-network

networks:
  imgpressor-network:
    driver: bridge
