name = "imgpressor"
compatibility_date = "2024-10-22"
pages_build_output_dir = "dist"

[env.production]
vars = { NODE_ENV = "production" }

[env.development]
vars = { NODE_ENV = "development" }

# For Cloudflare Workers (if using Workers instead of Pages Functions)
# main = "functions/_worker.js"
# compatibility_flags = ["nodejs_compat"]

# Build configuration for Pages
[build]
command = "npm run build:pages"
cwd = "."
watch_dir = ["src", "public"]

# Environment variables for build
[env.production.vars]
API_URL = "https://imgpressor.pages.dev"
NODE_ENV = "production"

[env.development.vars]
API_URL = "http://localhost:3000"
NODE_ENV = "development"