name = "imgpressor"
compatibility_date = "2024-10-22"
pages_build_output_dir = "dist"

# Cloudflare Pages deployment configuration

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
API_URL = "https://imgpressor.pages.dev"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "preview"
API_URL = "https://imgpressor-preview.pages.dev"