name = "imgpressor"
compatibility_date = "2024-10-22"
pages_build_output_dir = "dist"

# Build configuration for Pages
[build]
command = "npm run build:pages"
cwd = "."
watch_dir = ["src", "public"]

# Environment variables
[env.production.vars]
NODE_ENV = "production"
API_URL = "https://imgpressor.pages.dev"

[env.development.vars]
NODE_ENV = "development"
API_URL = "http://localhost:3000"